# fly.toml app configuration file generated for demo-web-fly on 2025-05-08T14:23:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-web-fly'
primary_region = 'sjc'

[build]
  image = 'docker.io/gdbenson/demo-web:1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
